baseurl: 'https://TrucJ.github.io'
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: TrucJ
disqusShortname: hugo-theme-stack
DefaultContentLanguage: en
hasCJKLanguage: false
publishDir: docs
languages:
  en:
    languageName: English
    title: TrucJ
    weight: 1
    params:
      description: Example description
  vn:
    languageName: Việt Nam
    title: TrucJ
    weight: 2
    params:
      description: VN example description
permalinks:
  post: '/p/:slug/'
  page: '/:slug/'
params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  footer:
    since: 2020
  dateFormat:
    published: 'Jan 02, 2006'
    lastUpdated: 'Jan 02, 2006 15:04 MST'
  sidebar:
    emoji: 🇻🇳
    subtitle: I'm Trung Truc, formerly a student at HCMUS, and currently, I work at ZaloPay.
    avatar:
      enabled: true
      local: true
      src: img/avatar.jpg
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: disqus
    disqusjs: {}
    utterances:
      issueTerm: pathname
    remark42: {}
    vssue:
      autoCreateIssue: false
    waline:
      emoji:
        - 'https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo'
      requiredMeta:
        - name
        - email
        - url
      locale:
        admin: Admin
    twikoo: {}
    cactus:
      defaultHomeserverUrl: 'https://matrix.cactus.chat:8448'
      serverName: cactus.chat
      siteName: ''
    giscus:
      reactionsEnabled: 1
      emitMetadata: 0
    gitalk: {}
    cusdis: {}
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc
  opengraph:
    twitter:
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  main: []
  social:
    - identifier: github
      name: GitHub
      url: 'https://github.com/TrucJ'
      weight: 1
      params:
        icon: brand-github
    - identifier: facebook
      name: Facebook
      url: 'https://www.facebook.com/profile.php?id=100009254438092'
      weight: 2
      params:
        icon: brand-facebook
    - identifier: linkedIn
      name: LinkedIn
      url: 'https://www.linkedin.com/in/TrucJ/'
      weight: 3
      params:
        icon: brand-linkedin
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
